### Errors

- Errors indicate an unwanted condition that occurs in our program. Whenever something unexpected happens, we get an error.
- `Go` has embedded support for errors that works in a simple way: functions return errors as their last return value. That means that we can check the error immediately before proceeding to the next steps of the function.
- In Go, many functions of packages contained in the Standard library have predefined errors:

```go
package main

import (
    "log"
    "os"
)

func main() {
    // Try to open a non-existing file: "new_file.txt"
    file, err := os.Open("new_file.txt") // os.Open returns two values: the file and an error
    if err != nil {
        log.Fatal(err) // Log the error & exit the program with the exit code 1 - meaning: general error
    }
    defer file.Close() // This line closes the file before exiting the program
}

// Output:
// 2022/10/04 06:09:55 open new_file.txt: The system cannot find the file specified.
```

The variable `err` is assigned to the second return value of the `os.Open` function, which is an `error` type value; `error` is an interface type declared in Go's builtin package that returns a `string` representation of the error message, and if there is no error, it returns `nil`.

In this example, since _new_file.txt_ doesn't exist, the value of `err` becomes the following error value: _"open new_file.txt: The system cannot find the file specified."_. When compared to `nil`, it evaluates to `true`, thus logging the error message into our terminal and finally exiting the program with the _exit code 1 â€” general error_.

### Creating custom errors

- _Go's Standard library_ offers two functions to create errors: `errors.New` from the errors package and `fmt.Errorf` from the fmt package.
- The difference between them is that `fmt.Errorf` provides the ability to add formatting to our error message, which means we can pass a parameter to the `fmt.Errorf` function and include it in the error message.

```go
// Implementation with errors.New
func divide (num1, num2 float64) (float64, error) {
    if num2 == 0 {
        return 0, errors.New("cannot divide by zero")
    }
    return num1 / num2, nil
}

// Output: cannot divide by zero
```

```go
// Implementation with fmt.Errorf
func divide (num1, num2 float64) (float64, error) {
    if num2 == 0 {
        return 0, fmt.Errorf("cannot divide %.2f by %.2f", num1, num2)
    }
    return num1 / num2, nil
}

// Output: cannot divide 10.00 by 0.00
```

### Wrapping errors
- In Go, when a function returns an error, it's common for the calling function to add more context by wrapping the error. This approach is often used to **provide clear information** on where in our program the error originated.
- We can create wrapped errors by using the ```%w``` verb with the ```fmt.Errorf``` function. Apart from that, we can also output the original error or unwrapped error via the ```errors.Unwrap``` function.
```go
package main

import (
    "errors"
    "fmt"
    "os"
)

// The function openFile returns a custom error message if opening the file fails
func openFile(filename string) error {
    if _, err := os.ReadFile(filename); err != nil {
        return fmt.Errorf("error opening %s: %w", filename, err)
    }

    return nil
}

func main() {
    err := openFile("new_file.txt")

    if err != nil {
        fmt.Printf("error running main.go: %s\n", err) // Print the wrapped error message

        unwrappedErr := errors.Unwrap(err) // This line unwraps the error
        fmt.Printf("unwrapped error: %s\n", unwrappedErr) // Print the original error message
    }
}
```
After executing this program, we will have the following output:
```go
error running main.go: error opening new_file.txt: open new_file.txt: The system cannot find the file specified.
unwrapped error: open new_file.txt: The system cannot find the file specified.
```